spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/book_exchange
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${app.port:8081}

